# Generated by Django 4.2.2 on 2023-06-29 19:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='order')),
                ('amount', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Order details',
                'verbose_name_plural': 'Orders Details',
                'db_table': 'apps_order_details',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='order')),
                ('date_order', models.DateField(auto_now_add=True)),
                ('state', models.CharField(choices=[('pending', 'Pendiente'), ('in_route', 'En Ruta'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado')], max_length=20)),
                ('paid', models.BooleanField(default=False)),
                ('shipping_rule', models.CharField(choices=[('home_delivery', 'Domicilio'), ('home_pick_up', 'Recoger')], max_length=20)),
                ('observations', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'apps_order',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='order')),
                ('name', models.CharField(max_length=50, verbose_name='product')),
                ('stock', models.IntegerField(verbose_name='stock')),
                ('price', models.FloatField(verbose_name='price')),
                ('description', models.TextField(verbose_name='description')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'apps_product',
                'ordering': ['order', 'id', 'name'],
            },
        ),
    ]
